version: "3.8"
services:
  database:
    container_name: mysqldb_bigbang
    image: mysql:8.0.24
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_node
      MYSQL_USER: styde
      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - 3306:3306
    volumes:
      - bigbangdata:/var/lib/mysql
    networks:
      - bigbang
networks:
  bigbang:
    driver: bridge
volumes:
  bigbangdata:
    driver: local
